### ISSUE TITLE
speech.bat在Windows 7無法辨識中文

### ISSUE THREAD

**Issue by chemars** [chemars/EEW_Extension#1]

**Comment by chemars** [comment]
試過 http://terryhung.pixnet.net/blog/post/34657057 ，可以讓Windows 7辨識中文，不過`speech.bat`還是無法播放中文

**Comment by chiyi4488** [comment]
UTF-8的關係嗎？

**Comment by chemars** [comment]
應該不是，我根據那篇文章再次在 Windows 7 32 位元和 64 位元測試，Windows 7 32 位元下是正常的， 64 位元下`speech.bat`還是無法播放中文（之前是只有在64 位元下測試）

**Comment by chiyi4488** [comment]
好吧（那我就不知道了）不過win7也要結束支援了（就別管他了吧😵）😅😅
