### ISSUE TITLE
建議加入nircmd

### ISSUE THREAD

**Issue by chiyi4488** [chemars/EEW_Extension#2]
我有個提案，加入nircmd在bat中，這樣就可以有更多的延伸空間，例如警報就可以撥mp3，也可以設定系統音量在警報時強制設定成100%之類的（以免原本開到靜音）

但bat就必須與nircmd.exe連結...不能像現在單個檔案...

我現在使用nircmd效果還不錯，需要附上程式碼給你看看嗎？：）

**Comment by chemars** [comment]
我是傾向於單純用bat跟PowerShell就好，如果要連結nircmd，你可以Fork這個repo，另外自訂音效現在地牛Wake Up!已經有內建了

**Comment by chiyi4488** [comment]
好吧
